# Chaque route décrit comment une IRL sera pris en charge par Plateform.sh
##

"https://{default}/":
    type: upstream
    upstream: "ll_project:http"

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"

